Addition endpoints for toolbox
Ameelio/letters-api pull request #90
Opened 2020-09-11 17:08 UTC by joyce-wu

2020-09-16 11:47 UTC, gabrielsaruhashi reviewed
hey @joyce-wu ! there are a couple of merge conflicts on this PR! could you check those out?

2020-09-16 11:48 UTC, gabrielsaruhashi requested changes
hey @joyce-wu there are a couple of merge conflicts that weren't resolved / large chunks of commented code. Could you take a look at those?

2020-09-21 12:15 UTC, gabrielsaruhashi requested changes
super cool! wrote a couple of comments 🔧

2020-09-21 12:15 UTC, gabrielsaruhashi commented on app/Jobs/SendNewsletter.php
> +            usleep(500000);
hey! there's still one conflict

2020-09-21 12:15 UTC, gabrielsaruhashi commented on app/Http/Controllers/UserController.php
> +
nit: wanna delete this extra space?

2020-09-21 12:15 UTC, gabrielsaruhashi commented on app/Http/Controllers/DesignCategoryController.php
> +      $total = $categories->count();
any way we can move this content range logic to a util file? It seems to be duplicated across all GET functions

2020-09-21 12:15 UTC, gabrielsaruhashi commented on app/Http/Controllers/AuthController.php
> +      $data = json_decode($request->getContent(), true);
what's the difference between this function and the plain login()
Couldnt we just use that?

Also, I think we're missing the  some layer of validation ot ensure the user is an Admin (and return 404 if not)

2020-09-21 17:07 UTC, gabrielsaruhashi approved these changes
🔥

2020-09-27 18:09 UTC, jessehorne approved these changes

2020-09-27 18:09 UTC, merged